server:
  port: "8080"
  readTimeout: 30
  writeTimeout: 30

postgres:
  host: "postgres"
  port: 5432
  user: "naxos"
  password: "naxos123"
  dbname: "naxos"
  sslmode: "disable"

rabbitmq:
  url: "amqp://naxos:naxos123@rabbitmq:5672/"
  exchange: "naxos"
  queue: "naxos.jobs"
  jobsQueue: "naxos.jobs"
  statusQueue: "naxos.status"
  exchangeType: "direct"

leveldb:
  path: "./data/leveldb"

worker:
  maxWorkers: 10
  maxRetries: 3
  retryDelay: 5
  shutdownTimeout: 30
