# docker-compose.yaml
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: naxos
      POSTGRES_PASSWORD: naxos123
      POSTGRES_DB: naxos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/postgres:/docker-entrypoint-initdb.d
    networks:
      - naxos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U naxos"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: naxos
      RABBITMQ_DEFAULT_PASS: naxos123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - naxos
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: naxos:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NAXOS_POSTGRES_URL: postgresql://naxos:naxos123@postgres:5432/naxos?sslmode=disable # mandatory
      NAXOS_RABBITMQ_URL: amqp://naxos:naxos123@rabbitmq:5672/ # mandatory
    ports:
      - "8080:8080"
    command: /app/api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - naxos

  orchestrator1:
    image: naxos:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NAXOS_POSTGRES_URL: postgresql://naxos:naxos123@postgres:5432/naxos?sslmode=disable # mandatory
      NAXOS_RABBITMQ_URL: amqp://naxos:naxos123@rabbitmq:5672/ # mandatory
    command: /app/orchestrator
    volumes:
      - leveldb_data1:/app/data/leveldb
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - naxos

  orchestrator2:
    image: naxos:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NAXOS_POSTGRES_URL: postgresql://naxos:naxos123@postgres:5432/naxos?sslmode=disable # mandatory
      NAXOS_RABBITMQ_URL: amqp://naxos:naxos123@rabbitmq:5672/ # mandatory
    command: /app/orchestrator
    volumes:
      - leveldb_data2:/app/data/leveldb
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - naxos

volumes:
  postgres_data:
  leveldb_data1:
  leveldb_data2:

networks:
  naxos:
